### ISSUE TITLE
可否发送一个已经下载好的 library 呢

### ISSUE THREAD

**Issue by wilddylan** [zlq4863947/tradingViewWikiCn#10]
<a href="mailto:dylan@china.com">dylan@china.com</a>

**Comment by wilddylan** [comment]
因为没有公司啊这些资质~ 还请大侠帮忙啊

**Comment by zlq4863947** [comment]
@WildDylan 
加qq群交流： 313839516

**Comment by wilddylan** [comment]
QQ 958226951 
邀请我一下
目前的状态是：群主任何新人加入

<img width="420" alt="default" src="https://user-images.githubusercontent.com/2519544/45143110-dcd2c980-b1ec-11e8-8878-1eca10130f79.png">

**Comment by zlq4863947** [comment]
@WildDylan  看下面的解决方法
#3

**Comment by wilddylan** [comment]
已经进去，library 在哪里下载呢。
