### ISSUE TITLE
干你全家妇女亲妈爆炸死垃圾

### ISSUE THREAD

**Issue by zzz-ss** [zlq4863947/tradingViewWikiCn#16]
操你妈的付费入群为什么把老子踢了？就因为把你老妈给草了？晚上等着给你妈收拾吧死废物

**Comment by zlq4863947** [comment]
@zzz-ss 你违反群规，收到问题红包不回答人家问题。
进群后仔细看群规，遵守群规。
另外文明用语，谢谢
