### ISSUE TITLE
请问在哪里申请license

### ISSUE THREAD

**Issue by Bubblex** [zlq4863947/tradingViewWikiCn#2]
![image](https://user-images.githubusercontent.com/22041769/33513221-4763cce4-d779-11e7-80dc-49ffd1bc2c96.png)

**Comment by zlq4863947** [comment]
https://cn.tradingview.com/HTML5-stock-forex-bitcoin-charting-library/
这个地址，点击下载图表库

你可以试试，有问题可以加qq群交流
