### ISSUE TITLE
你好，请问如何实现tradingview的websocket的呢？

### ISSUE THREAD

**Issue by chinalijinglun** [zlq4863947/tradingViewWikiCn#8]
你好，请问如何实现tradingview的websocket的呢？我想加您的qq群，但是拒绝任何人加入群。

**Comment by zlq4863947** [comment]
@chinalijinglun 
qq群可以加入的，现在群费10元。
mac版qq不支持付费入群，所以显示拒绝任何人加入。
你用手机qq加群就可以了
